/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cs_jnidemo_TestJni */

#ifndef _Included_com_cs_jnidemo_TestJni
#define _Included_com_cs_jnidemo_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cs_jnidemo_TestJni
 * Method:    getadd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cs_jnidemo_TestJni_getadd
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
